ItemEvents.tooltip(event => {
  // Add tooltip to all of these items
  event.add(['enigmaticaddons:lost_engine', ], '§4§lWill destroy items in your inventory if you get struck by lightning.')
  event.add(['morerelics:tyrant_mask', ], '§4§ktralala&r§4§lDISABLED ITEM, DO NOT USE.§ktralala&r')
  event.add(['ftbquests:book', ], '§8An Information Book for Linggango.')
  event.add(['lethality:tainted_blade', ], '§eUpgradeable sword.')
  event.add(['lethality:caustic_edge', ], '§eUpgradeable sword.')
  event.add(['lethality:blighted_cleaver', ], '§eUpgradeable sword.')
  event.add(['lethality:bladecrest_oathsword', ], '§eUpgradeable sword.')
  event.add(['lethality:forbidden_oathblade', ], '§eUpgradeable sword.')
  event.add(['lethality:exalted_oathblade', ], '§eUpgradeable sword.')
  event.add(['enigmaticaddons:bless_ring', ], '§b§lDo not equip it with Ring Of The Seven Curses at the same time.' )
  event.add(['brutality:pi_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:exponential_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:addition_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:subtraction_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:multiplication_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:division_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:sum_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:sine_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
  event.add(['brutality:cosine_charm', ], '&eRequires &aCalculator&r &eto use it!&r' )
 })

